language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli bower
script:
- grunt publish
branches:
  only:
    - master
env:
  global:
  - secure: eZuHm2/GU20EB9ukBHz64KFEheYPEiZC29RHKnYWz9qCsK3LL5pnQn4Apx03OdAOtB9Wc/IcHJzhUUxW4wjsElqqyszvHRFlXOVuPyv+fbSbqktba3xQEk4w/LO3fyJ8nwcUZwRQLDBsfyghIlnw60QodE+xeH9PjElxOc8azOA=
  - secure: ahJN+J8/V35MQEzVkMEyubV8xyEX9SX/Ug3W0pgSzp9Ii3dCk67gg5fjB+YA8J6ZbqkTRROFkC4rHZkXTp7fW2ddwhRxO8XHO4fDFIan83vzlCE1c3J7KoaRhgqPn+Alg434npICBUGqb2KVAhsK1PNHwaBcW8a0OhTg1+eR58k=
